"""empty message

Revision ID: efbaea5f8c6f
Revises: 
Create Date: 2025-05-26 19:59:08.149487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efbaea5f8c6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chemical',
    sa.Column('pubchem_id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.Text(), nullable=True),
    sa.Column('synonyms', sa.Text(), nullable=True),
    sa.Column('database', sa.Text(), nullable=True),
    sa.Column('iupac_name', sa.Text(), nullable=True),
    sa.Column('molecular_formula', sa.Text(), nullable=True),
    sa.Column('functional_group', sa.Text(), nullable=True),
    sa.Column('functional_group_idx', sa.Text(), nullable=True),
    sa.Column('smiles', sa.Text(), nullable=True),
    sa.Column('isomeric_smiles', sa.Text(), nullable=True),
    sa.Column('molecular_weight', sa.Float(), nullable=True),
    sa.Column('num_hydrogen_atoms', sa.Integer(), nullable=True),
    sa.Column('num_heavy_atoms', sa.Integer(), nullable=True),
    sa.Column('num_rings', sa.Integer(), nullable=True),
    sa.Column('num_rotatablebonds', sa.Integer(), nullable=True),
    sa.Column('number_of_aromatic_bonds', sa.Integer(), nullable=True),
    sa.Column('num_atoms', sa.Integer(), nullable=True),
    sa.Column('hba_count', sa.Integer(), nullable=True),
    sa.Column('hbd_count', sa.Integer(), nullable=True),
    sa.Column('hyrophilic_index', sa.Float(), nullable=True),
    sa.Column('alogp', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('pubchem_id')
    )
    with op.batch_alter_table('chemical', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chemical_common_name'), ['common_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemical_database'), ['database'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemical_functional_group'), ['functional_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemical_functional_group_idx'), ['functional_group_idx'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemical_iupac_name'), ['iupac_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_chemical_synonyms'), ['synonyms'], unique=False)

    op.create_table('disease',
    sa.Column('disease_id', sa.String(length=128), nullable=False),
    sa.Column('disease_name', sa.Text(), nullable=True),
    sa.Column('disease_synonyms', sa.Text(), nullable=True),
    sa.Column('disease_category', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('disease_id')
    )
    op.create_table('food',
    sa.Column('food_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('common_names', sa.Text(), nullable=True),
    sa.Column('scientific_name', sa.Text(), nullable=True),
    sa.Column('food_category', sa.String(length=128), nullable=True),
    sa.Column('tax_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('food_id')
    )
    op.create_table('gene',
    sa.Column('gene_id', sa.String(length=128), nullable=False),
    sa.Column('gene_name', sa.Text(), nullable=True),
    sa.Column('gene_symbol', sa.String(length=128), nullable=True),
    sa.Column('organism', sa.Text(), nullable=True),
    sa.Column('other_symbols', sa.Text(), nullable=True),
    sa.Column('synonyms', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('gene_id')
    )
    op.create_table('references',
    sa.Column('pmid', sa.Integer(), nullable=False),
    sa.Column('authors', sa.String(length=512), nullable=True),
    sa.Column('date', sa.String(length=128), nullable=True),
    sa.Column('journal_name', sa.String(length=512), nullable=True),
    sa.Column('journal_name_abbr', sa.String(length=512), nullable=True),
    sa.Column('publication_type', sa.String(length=512), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('pmid')
    )
    op.create_table('chemical_disease',
    sa.Column('pubchem_id', sa.String(length=128), nullable=False),
    sa.Column('disease_id', sa.String(length=128), nullable=False),
    sa.Column('type_relation', sa.String(length=512), nullable=True),
    sa.Column('via_genes', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.disease_id'], ),
    sa.ForeignKeyConstraint(['pubchem_id'], ['chemical.pubchem_id'], ),
    sa.PrimaryKeyConstraint('pubchem_id', 'disease_id')
    )
    op.create_table('chemical_gene',
    sa.Column('pubchem_id', sa.String(length=128), nullable=False),
    sa.Column('gene_id', sa.String(length=128), nullable=False),
    sa.Column('interaction_actions', sa.Text(), nullable=True),
    sa.Column('via_diseases', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['gene_id'], ['gene.gene_id'], ),
    sa.ForeignKeyConstraint(['pubchem_id'], ['chemical.pubchem_id'], ),
    sa.PrimaryKeyConstraint('pubchem_id', 'gene_id')
    )
    op.create_table('disease_gene',
    sa.Column('gene_id', sa.String(length=128), nullable=False),
    sa.Column('disease_id', sa.String(length=128), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('via_chemicals', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.disease_id'], ),
    sa.ForeignKeyConstraint(['gene_id'], ['gene.gene_id'], ),
    sa.PrimaryKeyConstraint('gene_id', 'disease_id')
    )
    op.create_table('food_chemical',
    sa.Column('food_id', sa.String(length=128), nullable=False),
    sa.Column('pubchem_id', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('type_relation', sa.String(length=100), nullable=True),
    sa.Column('inference_network', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['food.food_id'], ),
    sa.ForeignKeyConstraint(['pubchem_id'], ['chemical.pubchem_id'], ),
    sa.PrimaryKeyConstraint('food_id', 'pubchem_id')
    )
    op.create_table('food_disease',
    sa.Column('food_id', sa.String(length=128), nullable=False),
    sa.Column('disease_id', sa.String(length=128), nullable=False),
    sa.Column('positive_pmid', sa.String(length=512), nullable=True),
    sa.Column('negative_pmid', sa.String(length=512), nullable=True),
    sa.Column('pubchem_id', sa.String(length=512), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.disease_id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['food.food_id'], ),
    sa.PrimaryKeyConstraint('food_id', 'disease_id')
    )
    with op.batch_alter_table('food_disease', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_disease_weight'), ['weight'], unique=False)

    op.create_table('food_gene',
    sa.Column('food_id', sa.String(length=128), nullable=False),
    sa.Column('gene_id', sa.String(length=128), nullable=False),
    sa.Column('via_diseases', sa.String(length=512), nullable=True),
    sa.Column('via_chemicals', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['food.food_id'], ),
    sa.ForeignKeyConstraint(['gene_id'], ['gene.gene_id'], ),
    sa.PrimaryKeyConstraint('food_id', 'gene_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_gene')
    with op.batch_alter_table('food_disease', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_disease_weight'))

    op.drop_table('food_disease')
    op.drop_table('food_chemical')
    op.drop_table('disease_gene')
    op.drop_table('chemical_gene')
    op.drop_table('chemical_disease')
    op.drop_table('references')
    op.drop_table('gene')
    op.drop_table('food')
    op.drop_table('disease')
    with op.batch_alter_table('chemical', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chemical_synonyms'))
        batch_op.drop_index(batch_op.f('ix_chemical_iupac_name'))
        batch_op.drop_index(batch_op.f('ix_chemical_functional_group_idx'))
        batch_op.drop_index(batch_op.f('ix_chemical_functional_group'))
        batch_op.drop_index(batch_op.f('ix_chemical_database'))
        batch_op.drop_index(batch_op.f('ix_chemical_common_name'))

    op.drop_table('chemical')
    # ### end Alembic commands ###
